# Generated by Django 6.0.1 on 2026-01-15 08:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique reference used across the system provider', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paystack', 'Paystack')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='created', max_length=20)),
                ('raw_request', models.JSONField(blank=True, help_text='Initial request payload sent to provider', null=True)),
                ('raw_webhook', models.JSONField(blank=True, help_text='Last webhook payload received from provider', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='e.g STK_PUSH_SENT, WEBHOOK_RECEIVED', max_length=100)),
                ('payload', models.JSONField(help_text='Raw event payload')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
